name: Build and Publish Base Images

on:
  push:
    branches:
      - main
jobs:
  build-publish-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './images'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build -t ghcr.io/cfpb/regtech/sbl/alpine:3.18 -f Dockerfile-alpine .
          docker push ghcr.io/cfpb/regtech/sbl/alpine:3.1
