version: 0.2

env:
  variables:
    TEST_ONE: paul.bruno@cfpb.gov
    SMTP_CREDS_SECRET: cfpb/team/regtech/smtp-ses-creds
  secrets-manager:
    SMTP_PASSWORD: "${SMTP_CREDS_SECRET}:password"
    SMTP_PORT: "${SMTP_CREDS_SECRET}:smtp_port"
    SMTP_HOST: "${SMTP_CREDS_SECRET}:smtp_server"
    SMTP_USERNAME: "${SMTP_CREDS_SECRET}:username"
    TEST_SECRET_1: "cfpb/team/regtech/gha-codebuild-runner/test-secret-1:aa"
    TEST_SECRET_2: "cfpb/team/regtech/gha-codebuild-runner/test-secret-2:bb"
    TEST_SECRET_3: "cfpb/team/regtech/gha-codebuild-runner/test-secret-3:cc"
phases:
  install:
    commands:
      #- codebuild-init
      - kubectl version --client=true --output yaml
  pre_build:
    commands:
      - echo "TEST_SECRET_1 = ${TEST_SECRET_1}"
      - echo "TEST_SECRET_2 = ${TEST_SECRET_2}"
      - echo "TEST_SECRET_3 = ${TEST_SECRET_3}"
      - export IMAGE_NAME="cfpb/regtech/regtech-gha-codebuild-test"
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - export REGISTRY_IMAGE_NAME="${ECR_ACCOUNT_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
      #- export GITHUB_IMAGE_NAME="ghcr.io/cfpb/${IMAGE_NAME}:${IMAGE_TAG}"
      - env | sort
  post_build:
    commands:
      - pwd
      - ls -alt ../
      - docker pull docker pull ghcr.io/cfpb/regtech/sbl/python-ubi8:latest
      - docker tag ghcr.io/cfpb/regtech/sbl/python-ubi8:latest $REGISTRY_IMAGE_NAME
      #- git clone https://github.com/cfpb/regtech-deployments.git 
      #- docker build -t $REGISTRY_IMAGE_NAME -f "regtech-deployments/images/Dockerfile-alpine" .
      # push fails to ecr. needs creds. 
      # push also fails to ghcr, get token doesn't work error.
      #- docker push $REGISTRY_IMAGE_NAME
      #- aws sts get-caller-identity
      #- aws ecr list-images --repository-name cfpb/regtech/sbl-filing-api
