name: 'Mask Secrets'
description: 'Masking AWS Secrets'
inputs:
  secrets:
    description: 'string separated by EOL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Masking
      run: |
        while read -r line
        do
          echo "::add-mask::${line}"
        done <<< "${{ inputs.secrets }}"
      shell: bash
#    - name: Masking
#      run: |
#        echo "::add-mask::${{ inputs.secrets }}"
#      shell: bash
