name: 'Mask Secrets'
description: 'Masking AWS Secrets'
inputs:
  secrets:
    description: 'string separated by EOL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Masking
      run: |
        IFS="," read -a var <<< "${{ inputs.secrets }}"
        for x in "${var[@]}"; do
          echo "::add-mask::${{ env[$x] }}"
        done
      shell: bash
