name: 'Mask Secrets'
description: 'Masking AWS Secrets'
inputs:
  secrets:
    description: 'string separated by EOL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Masking
      run: |
        IFS=',' read -ra secrets <<< "${{ inputs.secrets }}"
        for secret in "${secrets[@]}" ; do
          echo -e "::add-mask::\"$secret\" ... registered"
        done
      shell: bash
#    - name: Masking
#      run: |
#        echo "::add-mask::${{ inputs.secrets }}"
#      shell: bash
