name: 'Mask Secrets'
description: 'Masking AWS Secrets'
inputs:
  secrets:
    description: 'string separated by EOL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Masking
      run: |
        IFS='\n' read -ra secrets <<< "${{ inputs.secrets }}"
        for secret in "${secrets[@]}" ; do
          if [[ "$secret" ]]; then
            echo "::add-mask::$secret ... registered"
          fi
        done
      shell: bash
