{{- if .Values.enabled -}}
{{- $values := .Values -}}
{{- range $mapping := .Values.mappings -}}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ $mapping.host }}-{{ randAlphaNum 8 }}
  namespace: {{ $values.target_namespace }}
spec:
{{ toYaml $mapping | indent 2 }}
  ambassador_id:
  - {{ $values.ambassador_id }}
{{ end }}
{{- end }}
