name: GHA Codebuild Runner Test

on:
  pull_request:
    branches: [main]

jobs:
  test1:
    runs-on:
      - codebuild-cfpb-regtech-gha-test-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |
          echo "force trigger again"
          echo -e "running GHS workflow ${{ github.event.number }}\nbuild: ${{ github.run_id }}\nattempt: ${{ github.run_attempt }}"
