name: CodebuildRunnerAWSSecret

on:
  pull_request:
    branches: [main]

jobs:
  test1:
    env:
    runs-on:
      - codebuild-cfpb-regtech-gha-test-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: get secrets from aws
        id: get-aws-secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            TEST_SECRET_1, cfpb/team/regtech/gha-codebuild-runner/test-secret-1
            TEST_SECRET_2, cfpb/team/regtech/gha-codebuild-runner/test-secret-2
            TEST_SECRET_3,arn:aws:secretsmanager:us-east-1:099248080076:secret:cfpb/team/regtech/gha-codebuild-runner/test-secret-3-9lVad8
      - name: check aws secrets
        id: check-aws-secrets
        run: |
          echo -e "show test-secret-1 ${{ env.TEST_SECRET_1 }}"
          echo -e "show test-secret-2 ${{ env.TEST_SECRET_2 }}"
          echo -e "show test-secret-3 ${{ env.TEST_SECRET_3 }}"
