name: GHA Codebuild Runner Test

on:
  pull_request:
    branches: [main]

jobs:
  test1:
    runs-on:
      - codebuild-cfpb-regtech-gha-test-1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: echo
        run: |
          echo "force trigger again"
          echo -e "running GHA workflow ${{ github.event.number }}\nbuild: ${{ github.run_id }}\nattempt: ${{ github.run_attempt }}"

      - name: create log stream
        run: |
          aws logs create-log-stream --log-group-name cfpb-regtech-gha-test-1 --log-stream-name ${{ github.run_id }}${{ github.run_number }}${{ github.run_attempt }}

      - name: list buckets
        run: |
          aws s3api list-buckets --region us-east-1 --output json

      - name: put events
        run: |
          gh run view ${{ github.run_id }} --log >runevents
          aws logs put-log-events --log-group-name cfpb-regtech-gha-test-1 --log-stream-name ${{ github.run_id }}${{ github.run_n    umber }}${{ github.run_attempt }} --log-events runevents

